### ISSUE TITLE
Symfony 4.2 autowiring for Audit Viewer

### ISSUE THREAD

**Issue by webmasterMeyers** [DamienHarper/DoctrineAuditBundle#36]
I have only been using Symfony for about 6 months now, and so I might be wrong with this but...

I would get an error when trying to use `$this->container->get('dh_doctrine_audit.reader');`

I had to put this in my services.yaml
```yaml
    DH\DoctrineAuditBundle\AuditReader:
        alias: dh_doctrine_audit.reader
    DH\DoctrineAuditBundle\AuditConfiguration:
        alias: dh_doctrine_audit.configuration
```
and then my controller
```php
use DH\DoctrineAuditBundle\AuditReader;

class AuditViewController extends AbstractController
{
    /**
     * @Route("/audit/view/{entity}/{id?0}", name="audit_view")
     */
    public function index(AuditReader $reader, $entity, $id)
    {
        $entity = 'App\Entity\\'.$entity;

        $data = $reader->getAudits($entity);
        dump($data);

        return $this->render('@DHDoctrineAudit/Audit/entity_audit_details.html.twig', [
            'entity' => $entity,
            'entry' => $data[$id],
        ]);
    }
}

```

**Would this be the correct approach?** and if so, might be worth putting in the readme!

Thanks for this, so far I think it will work.  I am having a couple issues with updated entities not getting tracked, but I have a lot more experimenting to do!  Damn complex forms.
