### ISSUE TITLE
listAuditsAction() is missing disabled entities

### ISSUE THREAD

**Issue by webmasterMeyers** [DamienHarper/DoctrineAuditBundle#58]
when viewing `example.com/audit` and entities with config `enabled: false` do not show up in the list.

ex;
````yaml
# config/packages/dh_doctrine_audit.yaml
dh_doctrine_audit:
    entities:
        App\Entity\ContactAddress:
            enabled: false
````
Contact Address will be omitted from the list even though you may have enabled audit at run time
