### ISSUE TITLE
Single table inheritance

### ISSUE THREAD

**Issue by MylesKingsnorth01** [DamienHarper/DoctrineAuditBundle#73]
I have an abstract entity which uses single table inheritance. Using a discriminator map, I'm mapping 3 entities that extend my abstract entity. 

In my `dh_doctrine_audit.yaml` under entities, I've put my parent class. Whenever I change one of the subclasses, no audits are created. I also did try splitting my audit config out by including the 3 entities individually. 

Here is my yaml config:

```yaml
dh_doctrine_audit:
    table_prefix: 'audit_'
    table_suffix: ''

    ignored_columns:
        - created
        - updated
        - createdBy
        - updatedBy

    entities:
        App\Entity\AbstractFooBar: ~
```

Here is the parent class:

```php
/**
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({
 *     "example_one" = "ExampleOne",
 *     "example_two" = "ExampleTwo",
 *     "example_three" = "ExampleThree"
 * })
 * @ORM\Entity()
 * @ORM\InheritanceType("SINGLE_TABLE")
 */
abstract class AbstractFooBar
{
    // ...
}
```

And then my three entities look like this:

```php
/**
 * @Entity()
 */
class ExampleOne extends AbstractFooBar
{
    // ...
}
```

Looking through the source code, there appears to be logic to audit these entities.
