### ISSUE TITLE
php bin/console audit:schema:update something with steps

### ISSUE THREAD

**Issue by mechemsi** [DamienHarper/DoctrineAuditBundle#85]
So I am trying to launch command ang I get "Unable to display the estimated time if the maximum number of steps is not set.". where do I set them?
php bin/console audit:schema:update
Introspecting schema...

                                                                               
  Unable to display the estimated time if the maximum number of steps is not   
  set.

**Comment by DamienHarper** [comment]
@mechemsi Thanks for the report, I've never encountered such an issue :/ 
I need to investigate a bit so can you tell me more about your environment: 
- what version of the bundle are you using? (latest stable or "unstable" `master` branch)
- what kind of database are you using and which version? (MySQL 8, Postgresql...)
- are you in the process of upgrading an already audited schema or are you setting up the bundle for the first time?

**Comment by mechemsi** [comment]
using 2.5 version
mysql 8 database
trying to set up for the first time with seperate database for audit log

**Comment by DamienHarper** [comment]
Thanks. I'll look at it in a few hours and keep you updated

**Comment by DamienHarper** [comment]
@mechemsi well, I can't find a way to reproduce the issue other than running the command on a system with no audited entity :/ 
Is that your case? Can you post your `dh_doctrine_audit.yaml` file?

Can you test `master` branch and provide some feedback?

**Comment by mechemsi** [comment]
Also bin/console doctrine:schema:update --force doesnt create audit tables now i checked, do not know why.

dh_doctrine_audit.yaml:

dh_doctrine_audit:
    enabled: true
    table_prefix: ''
    table_suffix: '_audit'
    entities:
        App\Entity\Company: ~

and services.yaml:
dh_doctrine_audit.manager:
        class: DH\DoctrineAuditBundle\AuditManager
        arguments: ["@dh_doctrine_audit.configuration", "@dh_doctrine_audit.helper", "@doctrine.orm.log_entity_manager"]
        public: true

    dh_doctrine_audit.event_subscriber.create_schema:
        class: DH\DoctrineAuditBundle\EventSubscriber\CreateSchemaListener
        arguments: ['@dh_doctrine_audit.manager']
        tags:
            - { name: doctrine.event_subscriber, connection: log }

**Comment by mechemsi** [comment]
okay with command ` php bin/console doctrine:schema:update --em=log --force` i created tables but needed to change entity manager settings to match default to create audit tables, but audit trying to insert data to default database instead to second one even when I have configured for second database as i posted above

**Comment by DamienHarper** [comment]
@mechemsi I'll update the `README.md` file to add the `--em` option when using a separate database, thanks for the reminder.

Then I don't really understand what you mean with:
> [...] but needed to change entity manager settings to match default to create audit tables, but audit trying to insert data to default database instead to second one even when I have configured for second database as i posted above

**Comment by mechemsi** [comment]
Yea for some reason some configuration of entity manager had to match default one , fields dir and prefix then audit tables are created in second database, but also main tables not only audit ones are created. But after creating audit tables in second database audit bundle makes sql query to insert data to default database (which doesnt have audit tables), when configuration is for other database where audit tables exist

**Comment by DamienHarper** [comment]
I'm going to try to reproduce on a test environment

**Comment by DamienHarper** [comment]
@mechemsi Can you test against `master` branch again please? I've just pushed some changes regarding using a secondary database to store audits.

**Note:** you have to change your `services.yaml` as described [here](https://github.com/DamienHarper/DoctrineAuditBundle#custom-database-for-storage-audit)

**Comment by mechemsi** [comment]
Now it is working, posting to second database, but found one configuration thing, if I only leave configuration in `services.yaml` as now described in documentation `doctrine:schema:update` doesn't create audit tables in second database, but if I use configuration like that:

    dh_doctrine_audit.manager:
        class: DH\DoctrineAuditBundle\AuditManager
        arguments: ["@dh_doctrine_audit.configuration", "@dh_doctrine_audit.helper", "@doctrine.orm.log_entity_manager"]
        #alias: dh_doctrine_audit.manager
        public: true

    dh_doctrine_audit.event_subscriber.create_schema:
        class: DH\DoctrineAuditBundle\EventSubscriber\CreateSchemaListener
        arguments: ['@dh_doctrine_audit.manager']
        tags:
            - { name: doctrine.event_subscriber, connection: log }

    dh_doctrine_audit.configuration:
        class: DH\DoctrineAuditBundle\AuditConfiguration
        arguments:
            - "%dh_doctrine_audit.configuration%"
            - "@dh_doctrine_audit.user_provider"
            - "@request_stack"
            - "@security.firewall.map"
            - "@doctrine.orm.log_entity_manager"

everything works fine, tables created in second database and audit sql executed to second database for audit

**Comment by DamienHarper** [comment]
@mechemsi well, I do not need such configuration to have it work: setting the dedicated (secondary) entity manager suffice in my test environment.

Here is my configuration as an example:
```yaml
# config/doctrine.yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: 'pdo_sqlite'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                url: '%env(resolve:DATABASE_URL)%'
            audits:
                driver: 'pdo_sqlite'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                url: '%env(resolve:AUDITS_DATABASE_URL)%'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            audits:
                connection: audits
                naming_strategy: doctrine.orm.naming_strategy.underscore
```
```yaml
# config/services.yaml
    dh_doctrine_audit.configuration:
        class: DH\DoctrineAuditBundle\AuditConfiguration
        arguments:
            - "%dh_doctrine_audit.configuration%"
            - "@dh_doctrine_audit.user_provider"
            - "@request_stack"
            - "@security.firewall.map"
            - "@doctrine.orm.audits_entity_manager"
```
Then, running `bin/console doctrine:schema:update --force` creates both regular tables in main database and audit tables in secondary database.

But, `bin/console doctrine:schema:update` only displays/counts queries that go to main database (queries related with a concrete entity precisely, which is not the case for audits as there are no entity mapped to audit_tables)

**Comment by mechemsi** [comment]
Okay thanks now it is completely working :)

**Comment by mechemsi** [comment]
`bin/console doctrine:schema:update --force` not creating now tables if i use configuration like yours for some reason, to create tables my entity manager config must be like this
                         
            log:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: log
                mappings:
                    Log:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Log

**Comment by DamienHarper** [comment]
@mechemsi can you post (or use a private gist if you prefer) your `doctrine.yaml` and `services.yaml` files please?

**Comment by mechemsi** [comment]
```yaml
# services.yaml
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    fos_user_fact:
        alias: fos_user.registration.form.factory
        public: true

#    fos_user.registration.form.factory:
#        class: FOS\UserBundle\Form\Factory\FormFactory

#    fos_rest.view_handler:
#        class: FOS\RestBundle\View\ViewHandler

    FOS\OAuthServerBundle\Entity\ClientManager:
        alias: fos_oauth_server.client_manager.default
        public: true

#    FOS\RestBundle\View\ViewHandler:
#        alias: fos_rest.view_handler
#        public: true


#    fos_rest:
#        format_listener:
#            rules:
#                - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }

    App\Command\OauthClientCreateCommand:
         arguments:
            $client_manager: '@fos_oauth_server.client_manager.default'

    app.form.registration:
        class: App\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

#    fos_rest.view_handler:
#        alias: fos_rest.view_handler.default

#    App\Command\:
#        resource: '../src/Command'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    #FOS\OAuthServerBundle\Document\ClientManager: ~

#    FOS\OAuthServerBundle\Document\ClientManager:
#        alias: fos_oauth_server.client_manager.default
#        public: true
#
#    FOS\OAuthServerBundle\Model\ClientManager: '@fos_oauth_server.client_manager.default'
    App\Service\FileUploader:
            arguments:
                $targetDirectory: 'tmp/'

#    dh_doctrine_audit.manager:
#        class: DH\DoctrineAuditBundle\AuditManager
#        arguments: ["@dh_doctrine_audit.configuration", "@dh_doctrine_audit.helper", "@doctrine.orm.log_entity_manager"]
#        #alias: dh_doctrine_audit.manager
#        public: true
#
#    dh_doctrine_audit.event_subscriber.create_schema:
#        class: DH\DoctrineAuditBundle\EventSubscriber\CreateSchemaListener
#        arguments: ['@dh_doctrine_audit.manager']
#        tags:
#            - { name: doctrine.event_subscriber, connection: log }

    dh_doctrine_audit.configuration:
        class: DH\DoctrineAuditBundle\AuditConfiguration
        arguments:
            - "%dh_doctrine_audit.configuration%"
            - "@dh_doctrine_audit.user_provider"
            - "@request_stack"
            - "@security.firewall.map"
            - "@doctrine.orm.log_entity_manager"
```
```yaml
# doctrine.yaml
parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''
    env(DATABASE_URL2): ''

doctrine:
    dbal:
        default_connection: default
        # configure these for your database server
        connections:
            default:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

                url: '%env(resolve:DATABASE_URL)%'
            log:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

                url: '%env(resolve:DATABASE_URL2)%'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App

            log:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: log
                mappings:
                    Log:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Log

#    dql:
#        datetime_functions:
#                test_datetime: App\DQL\DatetimeFunction
```
